version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - /home/hapax/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  #agent:
  #  image: jenkins/ssh-agent:jdk11
  #  privileged: true
  #  user: root
  #  container_name: agent
  #  expose:
  #    - 22
  #  networks:
  #    - jenkins
  #  environment:
  #    - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCw09JwvcZp0htkZoum8GQpA1c3cXx4GPrmG6z4KH5/fGDph5dvF4fYeYGfO7WrI3vy+QBZSq6mAjUJuemMtwMYrnQpg3I9NSdVkT17xABN8Dm/HSxfY10MXVlh7EwU5tL5t/qtkK1D07fFbFHE0BAL5uB+PN4BkKYQKF+6q3pyqTBotrQd95J7TQar5SdkjrVJzp8R0l+XDCW08uBY5tyOGc0xuv90hy/+s9Bkt+X9rbExbZUCGfoqk1KDeHB6YnyCoV0hp/4rTgELqiX5IjG5s3DjqHc+1dihnZHTFBe8XEJBxc0PeiIdEXqPYaLpQCBA5k7XGQLfUsHzD7jxY9voMvMVn5oKM9T7wkwz55pix4wQn/lMJiHUCY/WhTM331ftruW7Z+SDB8QIPscdI3d2WO+NCp+NkcccUg9yABocAx74HAr2e+VITUqCrt5+KdENdPQQU3mf+Yum/6iaT41oS32vWljJ/hSVjNMumAsTkh02moARpoh+7Hb8XqV14Lk= hapax@hapax-virtual-machine

networks:
  jenkins:
    name: jenkins-network